services:
  miner:
    build: .
    container_name: miner
    command: /bin/sh -c "./start-miner.sh --test"
    network_mode: "host"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WANDB_API_KEY: ${WANDB_API_KEY}
    volumes:
      - ./:/app
      - ${BT_WALLET_PATH:-~/.bittensor/wallets}:/root/.bittensor/wallets/
    working_dir: /app

  validator:
    build: .
    container_name: validator
    command: /bin/sh -c "./start-validator.sh --test"
    network_mode: "host"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WANDB_API_KEY: ${WANDB_API_KEY}
    volumes:
      - ./:/app
      - ${BT_WALLET_PATH:-~/.bittensor/wallets}:/root/.bittensor/wallets/
    working_dir: /app
