name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run pytest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest ./tests

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            source ~/.profile
            cd ${{ github.event.repository.name }}
            git pull origin main
            docker compose -f docker-compose.test.yml build
            docker compose -f docker-compose.test.yml up -d --force-recreate
